version: 0.2
phases:
  install:
    commands:
      - apt-get update
      - apt-get -y upgrade
      - apt-get install python python-pip build-essential -y
      - apt-get install zip unzip -y
      - pip install --upgrade pip
      - pip install --target ./package requests
      - pip install --target ./package requests_aws4auth
      - pip install --target ./package elasticsearch
  build:
    commands:
      - cd package
      - zip -r /tmp/index-photos.zip *
      - zip -r /tmp/search-photos.zip *
      - cd ../lambda/index-photos
      - zip -g /tmp/index-photos.zip lambda_function.py
      - cd ../search-photos
      - zip -g /tmp/search-photos.zip lambda_function.py
  post_build:
    commands:
      - cd /tmp
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://index-photos.zip
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://search-photos.zip
artifacts:
  files:
    - '/tmp/index-photos.zip'
    - '/tmp/search-photos.zip'